### ISSUE TITLE
Como llevas 2 anos y todavia ni le pones el HTML

### ISSUE THREAD

**Issue by anthony-fdez** [Almairy/Formulario-de-preguntas#1]
Ponte pa la cosa primo jajaja

**Comment by anthony-fdez** [comment]
@Almairy jona mojon nunca me respondiste

**Comment by Johnx199x** [comment]
Es que casi no entro aqui y no se como funcionan las cosas pero creo que ya lo  arregle, lo deje como lo tenia antes o como "debería" estar

**Comment by anthony-fdez** [comment]
> Es que casi no entro aqui y no se como funcionan las cosas pero creo que ya lo arregle, lo deje como lo tenia antes o como "debería" estar

no pongas excusas hahah ponte pa la cosa

**Comment by Johnx199x** [comment]
jeje
